@startuml Dastern Project - Use Case Diagram

!theme plain
left to right direction
skinparam packageStyle rectangle

actor User as user
actor System as system

rectangle "Dastern Medication Management System" {
  
  usecase "Manage Profile" as UC1
  usecase "Manage Medications" as UC2
  usecase "Manage Reminders" as UC3
  usecase "Track Intake" as UC4
  usecase "View Reports" as UC5
  usecase "Send Notifications" as UC6
}

' User relationships
user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

' System relationships
system --> UC6

' Relationships
UC6 ..> UC3 : <<extend>>
UC5 .> UC4 : <<include>>

@enduml